### ISSUE TITLE
I want to ask about GitHub Actions

### ISSUE THREAD

**Issue by TawfikYasser** [liununu/liununu#2]
Hi @liununu 

I want to learn how to make a github actions

Already I read the doecumentation but I still have problems

For example if I want to make a github action to update README file each push/PR

Thanks for your time.

**Comment by liununu** [comment]
Hi TawfikYasser,

Do you want to set a trigger for every time you push/pr? Maybe you could have a look about these references:

- https://docs.github.com/en/actions/reference/events-that-trigger-workflows
- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on

Hope that can help you.

**Comment by TawfikYasser** [comment]
Thank your very much. @liununu
